# Google Cloud Build configuration for OmniDash Frontend
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/omnidash-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/omnidash-frontend:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/omnidash-frontend:$COMMIT_SHA']
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/omnidash-frontend:latest']
    id: 'push-latest'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'omnidash-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/omnidash-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Configure build options
options:
  # Use high-performance machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Increase disk size for large builds
  diskSizeGb: 100
  # Enable logging
  logging: CLOUD_LOGGING_ONLY

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/omnidash-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/omnidash-frontend:latest'

# Build timeout (30 minutes)
timeout: '1800s'

# Substitutions for customization
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'omnidash-frontend'