global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OmniDash Backend API
  - job_name: 'omnidash-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # OmniDash Frontend
  - job_name: 'omnidash-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL Exporter (if deployed)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter (if deployed)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx Exporter (if deployed)
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Google Cloud Monitoring (if configured)
  - job_name: 'gcp-monitoring'
    static_configs:
      - targets: ['gcp-monitoring:9090']
    scrape_interval: 60s

  # Custom application metrics
  - job_name: 'omnidash-custom-metrics'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/custom-metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
