# Google Cloud Build configuration for OmniDash V2
# Automatically builds and deploys from GitHub when changes are pushed

steps:
  # Install dependencies and build frontend
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd omnidash-frontend
        npm ci
        npm run build
        echo "✅ Frontend build completed"

  # Build Docker image for Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/omnidash-frontend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/omnidash-frontend:latest'
      - '.'

  # Push to Container Registry  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/omnidash-frontend:$BUILD_ID'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'omnidash-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/omnidash-frontend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'