#!/bin/bash
# Emergency deployment script if automatic deployment isn't working
# This script will deploy directly using Google Cloud Shell

echo "🚀 OmniDash V2 Emergency Deployment Script"
echo "========================================"
echo ""
echo "1. Open Google Cloud Shell: https://shell.cloud.google.com"
echo "2. Run these commands:"
echo ""
echo "# Clone your repository"
echo "git clone https://github.com/steeldragon666/OmniDashV2.git"
echo "cd OmniDashV2"
echo ""
echo "# Set your project (replace YOUR_PROJECT_ID)"
echo "export PROJECT_ID=YOUR_PROJECT_ID"
echo "gcloud config set project \$PROJECT_ID"
echo ""
echo "# Enable required APIs"
echo "gcloud services enable cloudbuild.googleapis.com"
echo "gcloud services enable run.googleapis.com"
echo "gcloud services enable containerregistry.googleapis.com"
echo ""
echo "# Build and deploy"
echo "cd omnidash-frontend"
echo "gcloud builds submit --tag gcr.io/\$PROJECT_ID/omnidash-frontend ."
echo ""
echo "# Deploy to Cloud Run"
echo "gcloud run deploy omnidash-frontend \\"
echo "  --image gcr.io/\$PROJECT_ID/omnidash-frontend \\"
echo "  --region us-central1 \\"
echo "  --platform managed \\"
echo "  --allow-unauthenticated \\"
echo "  --port 3000 \\"
echo "  --memory 2Gi \\"
echo "  --cpu 2 \\"
echo "  --max-instances 10"
echo ""
echo "🎉 Your app will be live at: https://omnidash-frontend-\$PROJECT_ID.a.run.app"